cosa_frontend:
    resource: "@CosaFrontendBundle/Resources/config/routing.yml"
    prefix:   /

cosa_contact:
    resource: "@CosaContactBundle/Resources/config/routing.yml"
    prefix:   /

cosa_category:
    resource: "@CosaCategoryBundle/Resources/config/routing.yml"
    prefix:   /

cosa_navigation:
    resource: "@CosaNavigationBundle/Resources/config/routing.yml"
    prefix:   /

cosa_page:
    resource: "@CosaPageBundle/Resources/config/routing.yml"
    prefix:   /

cosa_admin:
    resource: "@CosaAdminBundle/Resources/config/routing.yml"
    prefix:   /

cosa_user:
    resource: "@CosaUserBundle/Resources/config/routing.yml"
    prefix:   /

#cosa_payment:
#    resource: "@CosaPaymentBundle/Resources/config/routing.yml"
#    prefix:   /

asiel_config:
    resource: .
    type: extra
    prefix: /administration/settings/


# ADMIN
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /administration

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administration

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administration
