security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Cosa\UserBundle\Entity\FrontendUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        user_backend:
            id: fos_user.user_manager
        user_frontend:
            entity: { class: CosaUserBundle:FrontendUser, property: username }

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /administration(.*)
            context:            user
            form_login:
                provider:       user_backend
                login_path:     /administration/login
                use_forward:    false
                check_path:     /administration/login_check
                failure_path:   null
                default_target_path: /administration/dashboard
            logout:
                path:           /administration/logout
            anonymous:          true

        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       user_frontend
                login_path:     /user/login/
                use_forward:    false
#                check_path:     /login_check
                always_use_default_target_path: true
                default_target_path: /user/account/
                failure_path:   true
            logout:
                path:           /user/logout/
                target:         /
            anonymous:          true
#            logout:             true
#            security:           true
#            use_forward:        true


    access_control:
        # Frontend
        - { path: ^/user/login/, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/password/forgot/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/.*, role: [ROLE_USER] }
        - { path: ^/payment/.*, role: [ROLE_USER] }

        # Admin login page needs to be access without credential
        - { path: ^/administration/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/administration/.*, role: [ROLE_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }