api_cosa_categorylist:
    pattern:  /api/category/list.json
    defaults: { _controller: CosaCategoryBundle:Api:categoryList, _format: json }
    requirements:
        _method: GET

api_cosa_categoryview:
    pattern:  /api/category/view/{urlKey}.json
    defaults: { _controller: CosaCategoryBundle:Api:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"

api_cosa_categorytree:
    pattern:  /api/category/tree.json
    defaults: { _controller: CosaCategoryBundle:Api:categoryTree, _format: json }
    requirements:
        _method: GET


cosa_categoryview:
    pattern:  /category/{urlKey}/
    defaults: { _controller: CosaCategoryBundle:Frontend:categoryView }

